"""
Django settings for clientes project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# ==============================================================================
# BASE DIRECTORY
# ==============================================================================


BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# CORE SETTINGS
# ==============================================================================

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3bt0ngd5=ge=tbid#s=h*s6us7s)j1)ggfe#=2u#4ydej5=uw7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [] # En producción, aquí irían los dominios permitidos (ej. ['tudominio.com'])


# ==============================================================================
# APPLICATION DEFINITION
# ==============================================================================

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # Custom apps
    'todo', #Aplicación principal
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clientes.urls'


LOGIN_URL = 'signIn' 
LOGIN_REDIRECT_URL = 'home' 


# ==============================================================================
# TEMPLATES
# ==============================================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clientes.wsgi.application'


# ==============================================================================
# DATABASE
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# ==============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bd_veluweb',
        'USER': 'postgres',
        'PASSWORD': 'skividitoilet',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# ==============================================================================
# PASSWORD VALIDATION
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,  #  mínimo 8 caracteres
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "todo.validators.CustomPasswordValidator",  # 👈 aquí va tu validador propio
    },
]

# Configuración para usar un backend de autenticación personalizado (por ejemplo, con email)
AUTHENTICATION_BACKENDS = ['todo.backend.EmailBackend']


# ==============================================================================
# INTERNATIONALIZATION & TIME
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# ==============================================================================

LANGUAGE_CODE = 'es-co' # Cambiado a español de Colombia, si aplica
TIME_ZONE = 'America/Bogota' # Cambiado a la zona horaria de Ibagué/Bogotá, si aplica

USE_I18N = True # Habilita la internacionalización

USE_TZ = True # Habilita zonas horarias (muy recomendable)


# ==============================================================================
# STATIC FILES (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# ==============================================================================

STATIC_URL = 'static/'


STATICFILES_DIRS = [
    BASE_DIR / 'static', 
]


#STATIC_ROOT = BASE_DIR / 'staticfiles'


# ==============================================================================
# MEDIA FILES (User-uploaded files)
# ==============================================================================

MEDIA_URL = '/media/' 
MEDIA_ROOT = BASE_DIR / 'media' 


# ==============================================================================
# EMAIL SETTINGS (SMTP)
# ==============================================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'veluweb1@gmail.com'
EMAIL_HOST_PASSWORD = 'ovci rkne cyqe evqn' # Considera usar variables de entorno para esto
DEFAULT_FROM_EMAIL = 'veluweb1@gmail.com'


# ==============================================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
# ==============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==========================
# Configuración de Sesiones
# ==========================

SESSION_COOKIE_AGE = 900



# Refresca el tiempo de expiración
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True